In [2]:
import numpy as np

In [13]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [14]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [22]:
np.random.rand(2,2)

array([[0.32466882, 0.4523951 ],
       [0.61786194, 0.91073989]])

In [25]:
mlist = ['Ryan Gosling' '37' '1' '2']
arr = np.array(mlist)
arr

array(['Ryan Gosling3712'], dtype='<U16')

In [28]:
np.arange(1,100,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [38]:
a = np.random.rand(10,10)
a.shape

(10, 10)

In [40]:
a.reshape(5,5,4)
a

array([[0.72213945, 0.10545378, 0.37186848, 0.35372956, 0.31905243,
        0.64705466, 0.75856986, 0.66312612, 0.04730448, 0.94590848],
       [0.59727582, 0.00969381, 0.5242569 , 0.84772603, 0.20720952,
        0.24038172, 0.25111892, 0.07808917, 0.28963913, 0.18196738],
       [0.53170257, 0.42737389, 0.37247378, 0.34187668, 0.81280806,
        0.06919415, 0.01907553, 0.62684146, 0.68568684, 0.10325419],
       [0.71979434, 0.31405334, 0.95063687, 0.17722129, 0.91265569,
        0.69237294, 0.79455307, 0.67257854, 0.23651153, 0.08598695],
       [0.03947318, 0.80850546, 0.45869588, 0.83014287, 0.59895557,
        0.40287503, 0.51678503, 0.79332944, 0.65115033, 0.13210307],
       [0.86071739, 0.61983535, 0.92578733, 0.93861278, 0.47257423,
        0.24766196, 0.26424908, 0.64164205, 0.68551817, 0.00629721],
       [0.25450092, 0.21267051, 0.64501408, 0.16275715, 0.61380015,
        0.39219081, 0.48585636, 0.49893919, 0.30877123, 0.05160142],
       [0.23051442, 0.36043009, 0.1296609

In [42]:
a.dtype

dtype('float64')

In [45]:
a.ndim

2